-- ============================================================
-- WorldNotes — FULL country list
-- Run ONCE in the Supabase SQL editor (after supabase-setup.sql).
--
-- Seeds every current sovereign state (~197, incl. Taiwan, Kosovo,
-- Palestine, Vatican), notable defunct currency-issuing states
-- (USSR, Rhodesia, Ottoman Empire, Biafra, …) and unrecognized
-- states (Somaliland, Transnistria, …).
--
-- Statuses used: 'active' | 'defunct' | 'unrecognized'
-- Defunct + unrecognized live under the "Defunct / Unrecognized"
-- continent, matching the existing seed convention.
--
-- Safe to re-run: upserts by country name (adds a unique index on
-- name first — the starter seed has no duplicates, so this is safe).
-- ============================================================

create unique index if not exists countries_name_key on countries (name);

insert into countries (continent_id, name, iso_code, flag_emoji, status) values
-- ---------------- AFRICA (54) ----------------
((select id from continents where name='Africa'),'Algeria','DZ','🇩🇿','active'),
((select id from continents where name='Africa'),'Angola','AO','🇦🇴','active'),
((select id from continents where name='Africa'),'Benin','BJ','🇧🇯','active'),
((select id from continents where name='Africa'),'Botswana','BW','🇧🇼','active'),
((select id from continents where name='Africa'),'Burkina Faso','BF','🇧🇫','active'),
((select id from continents where name='Africa'),'Burundi','BI','🇧🇮','active'),
((select id from continents where name='Africa'),'Cabo Verde','CV','🇨🇻','active'),
((select id from continents where name='Africa'),'Cameroon','CM','🇨🇲','active'),
((select id from continents where name='Africa'),'Central African Republic','CF','🇨🇫','active'),
((select id from continents where name='Africa'),'Chad','TD','🇹🇩','active'),
((select id from continents where name='Africa'),'Comoros','KM','🇰🇲','active'),
((select id from continents where name='Africa'),'Republic of the Congo','CG','🇨🇬','active'),
((select id from continents where name='Africa'),'DR Congo','CD','🇨🇩','active'),
((select id from continents where name='Africa'),'Côte d''Ivoire','CI','🇨🇮','active'),
((select id from continents where name='Africa'),'Djibouti','DJ','🇩🇯','active'),
((select id from continents where name='Africa'),'Egypt','EG','🇪🇬','active'),
((select id from continents where name='Africa'),'Equatorial Guinea','GQ','🇬🇶','active'),
((select id from continents where name='Africa'),'Eritrea','ER','🇪🇷','active'),
((select id from continents where name='Africa'),'Eswatini','SZ','🇸🇿','active'),
((select id from continents where name='Africa'),'Ethiopia','ET','🇪🇹','active'),
((select id from continents where name='Africa'),'Gabon','GA','🇬🇦','active'),
((select id from continents where name='Africa'),'Gambia','GM','🇬🇲','active'),
((select id from continents where name='Africa'),'Ghana','GH','🇬🇭','active'),
((select id from continents where name='Africa'),'Guinea','GN','🇬🇳','active'),
((select id from continents where name='Africa'),'Guinea-Bissau','GW','🇬🇼','active'),
((select id from continents where name='Africa'),'Kenya','KE','🇰🇪','active'),
((select id from continents where name='Africa'),'Lesotho','LS','🇱🇸','active'),
((select id from continents where name='Africa'),'Liberia','LR','🇱🇷','active'),
((select id from continents where name='Africa'),'Libya','LY','🇱🇾','active'),
((select id from continents where name='Africa'),'Madagascar','MG','🇲🇬','active'),
((select id from continents where name='Africa'),'Malawi','MW','🇲🇼','active'),
((select id from continents where name='Africa'),'Mali','ML','🇲🇱','active'),
((select id from continents where name='Africa'),'Mauritania','MR','🇲🇷','active'),
((select id from continents where name='Africa'),'Mauritius','MU','🇲🇺','active'),
((select id from continents where name='Africa'),'Morocco','MA','🇲🇦','active'),
((select id from continents where name='Africa'),'Mozambique','MZ','🇲🇿','active'),
((select id from continents where name='Africa'),'Namibia','NA','🇳🇦','active'),
((select id from continents where name='Africa'),'Niger','NE','🇳🇪','active'),
((select id from continents where name='Africa'),'Nigeria','NG','🇳🇬','active'),
((select id from continents where name='Africa'),'Rwanda','RW','🇷🇼','active'),
((select id from continents where name='Africa'),'São Tomé and Príncipe','ST','🇸🇹','active'),
((select id from continents where name='Africa'),'Senegal','SN','🇸🇳','active'),
((select id from continents where name='Africa'),'Seychelles','SC','🇸🇨','active'),
((select id from continents where name='Africa'),'Sierra Leone','SL','🇸🇱','active'),
((select id from continents where name='Africa'),'Somalia','SO','🇸🇴','active'),
((select id from continents where name='Africa'),'South Africa','ZA','🇿🇦','active'),
((select id from continents where name='Africa'),'South Sudan','SS','🇸🇸','active'),
((select id from continents where name='Africa'),'Sudan','SD','🇸🇩','active'),
((select id from continents where name='Africa'),'Tanzania','TZ','🇹🇿','active'),
((select id from continents where name='Africa'),'Togo','TG','🇹🇬','active'),
((select id from continents where name='Africa'),'Tunisia','TN','🇹🇳','active'),
((select id from continents where name='Africa'),'Uganda','UG','🇺🇬','active'),
((select id from continents where name='Africa'),'Zambia','ZM','🇿🇲','active'),
((select id from continents where name='Africa'),'Zimbabwe','ZW','🇿🇼','active'),
-- ---------------- ASIA (48) ----------------
((select id from continents where name='Asia'),'Afghanistan','AF','🇦🇫','active'),
((select id from continents where name='Asia'),'Armenia','AM','🇦🇲','active'),
((select id from continents where name='Asia'),'Azerbaijan','AZ','🇦🇿','active'),
((select id from continents where name='Asia'),'Bahrain','BH','🇧🇭','active'),
((select id from continents where name='Asia'),'Bangladesh','BD','🇧🇩','active'),
((select id from continents where name='Asia'),'Bhutan','BT','🇧🇹','active'),
((select id from continents where name='Asia'),'Brunei','BN','🇧🇳','active'),
((select id from continents where name='Asia'),'Cambodia','KH','🇰🇭','active'),
((select id from continents where name='Asia'),'China','CN','🇨🇳','active'),
((select id from continents where name='Asia'),'Georgia','GE','🇬🇪','active'),
((select id from continents where name='Asia'),'India','IN','🇮🇳','active'),
((select id from continents where name='Asia'),'Indonesia','ID','🇮🇩','active'),
((select id from continents where name='Asia'),'Iran','IR','🇮🇷','active'),
((select id from continents where name='Asia'),'Iraq','IQ','🇮🇶','active'),
((select id from continents where name='Asia'),'Israel','IL','🇮🇱','active'),
((select id from continents where name='Asia'),'Japan','JP','🇯🇵','active'),
((select id from continents where name='Asia'),'Jordan','JO','🇯🇴','active'),
((select id from continents where name='Asia'),'Kazakhstan','KZ','🇰🇿','active'),
((select id from continents where name='Asia'),'Kuwait','KW','🇰🇼','active'),
((select id from continents where name='Asia'),'Kyrgyzstan','KG','🇰🇬','active'),
((select id from continents where name='Asia'),'Laos','LA','🇱🇦','active'),
((select id from continents where name='Asia'),'Lebanon','LB','🇱🇧','active'),
((select id from continents where name='Asia'),'Malaysia','MY','🇲🇾','active'),
((select id from continents where name='Asia'),'Maldives','MV','🇲🇻','active'),
((select id from continents where name='Asia'),'Mongolia','MN','🇲🇳','active'),
((select id from continents where name='Asia'),'Myanmar','MM','🇲🇲','active'),
((select id from continents where name='Asia'),'Nepal','NP','🇳🇵','active'),
((select id from continents where name='Asia'),'North Korea','KP','🇰🇵','active'),
((select id from continents where name='Asia'),'Oman','OM','🇴🇲','active'),
((select id from continents where name='Asia'),'Pakistan','PK','🇵🇰','active'),
((select id from continents where name='Asia'),'Palestine','PS','🇵🇸','active'),
((select id from continents where name='Asia'),'Philippines','PH','🇵🇭','active'),
((select id from continents where name='Asia'),'Qatar','QA','🇶🇦','active'),
((select id from continents where name='Asia'),'Saudi Arabia','SA','🇸🇦','active'),
((select id from continents where name='Asia'),'Singapore','SG','🇸🇬','active'),
((select id from continents where name='Asia'),'South Korea','KR','🇰🇷','active'),
((select id from continents where name='Asia'),'Sri Lanka','LK','🇱🇰','active'),
((select id from continents where name='Asia'),'Syria','SY','🇸🇾','active'),
((select id from continents where name='Asia'),'Taiwan','TW','🇹🇼','active'),
((select id from continents where name='Asia'),'Tajikistan','TJ','🇹🇯','active'),
((select id from continents where name='Asia'),'Thailand','TH','🇹🇭','active'),
((select id from continents where name='Asia'),'Timor-Leste','TL','🇹🇱','active'),
((select id from continents where name='Asia'),'Turkey','TR','🇹🇷','active'),
((select id from continents where name='Asia'),'Turkmenistan','TM','🇹🇲','active'),
((select id from continents where name='Asia'),'United Arab Emirates','AE','🇦🇪','active'),
((select id from continents where name='Asia'),'Uzbekistan','UZ','🇺🇿','active'),
((select id from continents where name='Asia'),'Vietnam','VN','🇻🇳','active'),
((select id from continents where name='Asia'),'Yemen','YE','🇾🇪','active'),
-- ---------------- EUROPE (46) ----------------
((select id from continents where name='Europe'),'Albania','AL','🇦🇱','active'),
((select id from continents where name='Europe'),'Andorra','AD','🇦🇩','active'),
((select id from continents where name='Europe'),'Austria','AT','🇦🇹','active'),
((select id from continents where name='Europe'),'Belarus','BY','🇧🇾','active'),
((select id from continents where name='Europe'),'Belgium','BE','🇧🇪','active'),
((select id from continents where name='Europe'),'Bosnia and Herzegovina','BA','🇧🇦','active'),
((select id from continents where name='Europe'),'Bulgaria','BG','🇧🇬','active'),
((select id from continents where name='Europe'),'Croatia','HR','🇭🇷','active'),
((select id from continents where name='Europe'),'Cyprus','CY','🇨🇾','active'),
((select id from continents where name='Europe'),'Czechia','CZ','🇨🇿','active'),
((select id from continents where name='Europe'),'Denmark','DK','🇩🇰','active'),
((select id from continents where name='Europe'),'Estonia','EE','🇪🇪','active'),
((select id from continents where name='Europe'),'Finland','FI','🇫🇮','active'),
((select id from continents where name='Europe'),'France','FR','🇫🇷','active'),
((select id from continents where name='Europe'),'Germany','DE','🇩🇪','active'),
((select id from continents where name='Europe'),'Greece','GR','🇬🇷','active'),
((select id from continents where name='Europe'),'Hungary','HU','🇭🇺','active'),
((select id from continents where name='Europe'),'Iceland','IS','🇮🇸','active'),
((select id from continents where name='Europe'),'Ireland','IE','🇮🇪','active'),
((select id from continents where name='Europe'),'Italy','IT','🇮🇹','active'),
((select id from continents where name='Europe'),'Kosovo','XK','🇽🇰','active'),
((select id from continents where name='Europe'),'Latvia','LV','🇱🇻','active'),
((select id from continents where name='Europe'),'Liechtenstein','LI','🇱🇮','active'),
((select id from continents where name='Europe'),'Lithuania','LT','🇱🇹','active'),
((select id from continents where name='Europe'),'Luxembourg','LU','🇱🇺','active'),
((select id from continents where name='Europe'),'Malta','MT','🇲🇹','active'),
((select id from continents where name='Europe'),'Moldova','MD','🇲🇩','active'),
((select id from continents where name='Europe'),'Monaco','MC','🇲🇨','active'),
((select id from continents where name='Europe'),'Montenegro','ME','🇲🇪','active'),
((select id from continents where name='Europe'),'Netherlands','NL','🇳🇱','active'),
((select id from continents where name='Europe'),'North Macedonia','MK','🇲🇰','active'),
((select id from continents where name='Europe'),'Norway','NO','🇳🇴','active'),
((select id from continents where name='Europe'),'Poland','PL','🇵🇱','active'),
((select id from continents where name='Europe'),'Portugal','PT','🇵🇹','active'),
((select id from continents where name='Europe'),'Romania','RO','🇷🇴','active'),
((select id from continents where name='Europe'),'Russia','RU','🇷🇺','active'),
((select id from continents where name='Europe'),'San Marino','SM','🇸🇲','active'),
((select id from continents where name='Europe'),'Serbia','RS','🇷🇸','active'),
((select id from continents where name='Europe'),'Slovakia','SK','🇸🇰','active'),
((select id from continents where name='Europe'),'Slovenia','SI','🇸🇮','active'),
((select id from continents where name='Europe'),'Spain','ES','🇪🇸','active'),
((select id from continents where name='Europe'),'Sweden','SE','🇸🇪','active'),
((select id from continents where name='Europe'),'Switzerland','CH','🇨🇭','active'),
((select id from continents where name='Europe'),'Ukraine','UA','🇺🇦','active'),
((select id from continents where name='Europe'),'United Kingdom','GB','🇬🇧','active'),
((select id from continents where name='Europe'),'Vatican City','VA','🇻🇦','active'),
-- ---------------- AMERICAS (35) ----------------
((select id from continents where name='Americas'),'Antigua and Barbuda','AG','🇦🇬','active'),
((select id from continents where name='Americas'),'Argentina','AR','🇦🇷','active'),
((select id from continents where name='Americas'),'Bahamas','BS','🇧🇸','active'),
((select id from continents where name='Americas'),'Barbados','BB','🇧🇧','active'),
((select id from continents where name='Americas'),'Belize','BZ','🇧🇿','active'),
((select id from continents where name='Americas'),'Bolivia','BO','🇧🇴','active'),
((select id from continents where name='Americas'),'Brazil','BR','🇧🇷','active'),
((select id from continents where name='Americas'),'Canada','CA','🇨🇦','active'),
((select id from continents where name='Americas'),'Chile','CL','🇨🇱','active'),
((select id from continents where name='Americas'),'Colombia','CO','🇨🇴','active'),
((select id from continents where name='Americas'),'Costa Rica','CR','🇨🇷','active'),
((select id from continents where name='Americas'),'Cuba','CU','🇨🇺','active'),
((select id from continents where name='Americas'),'Dominica','DM','🇩🇲','active'),
((select id from continents where name='Americas'),'Dominican Republic','DO','🇩🇴','active'),
((select id from continents where name='Americas'),'Ecuador','EC','🇪🇨','active'),
((select id from continents where name='Americas'),'El Salvador','SV','🇸🇻','active'),
((select id from continents where name='Americas'),'Grenada','GD','🇬🇩','active'),
((select id from continents where name='Americas'),'Guatemala','GT','🇬🇹','active'),
((select id from continents where name='Americas'),'Guyana','GY','🇬🇾','active'),
((select id from continents where name='Americas'),'Haiti','HT','🇭🇹','active'),
((select id from continents where name='Americas'),'Honduras','HN','🇭🇳','active'),
((select id from continents where name='Americas'),'Jamaica','JM','🇯🇲','active'),
((select id from continents where name='Americas'),'Mexico','MX','🇲🇽','active'),
((select id from continents where name='Americas'),'Nicaragua','NI','🇳🇮','active'),
((select id from continents where name='Americas'),'Panama','PA','🇵🇦','active'),
((select id from continents where name='Americas'),'Paraguay','PY','🇵🇾','active'),
((select id from continents where name='Americas'),'Peru','PE','🇵🇪','active'),
((select id from continents where name='Americas'),'Saint Kitts and Nevis','KN','🇰🇳','active'),
((select id from continents where name='Americas'),'Saint Lucia','LC','🇱🇨','active'),
((select id from continents where name='Americas'),'Saint Vincent and the Grenadines','VC','🇻🇨','active'),
((select id from continents where name='Americas'),'Suriname','SR','🇸🇷','active'),
((select id from continents where name='Americas'),'Trinidad and Tobago','TT','🇹🇹','active'),
((select id from continents where name='Americas'),'USA','US','🇺🇸','active'),
((select id from continents where name='Americas'),'Uruguay','UY','🇺🇾','active'),
((select id from continents where name='Americas'),'Venezuela','VE','🇻🇪','active'),
-- ---------------- OCEANIA (14) ----------------
((select id from continents where name='Oceania'),'Australia','AU','🇦🇺','active'),
((select id from continents where name='Oceania'),'Fiji','FJ','🇫🇯','active'),
((select id from continents where name='Oceania'),'Kiribati','KI','🇰🇮','active'),
((select id from continents where name='Oceania'),'Marshall Islands','MH','🇲🇭','active'),
((select id from continents where name='Oceania'),'Micronesia','FM','🇫🇲','active'),
((select id from continents where name='Oceania'),'Nauru','NR','🇳🇷','active'),
((select id from continents where name='Oceania'),'New Zealand','NZ','🇳🇿','active'),
((select id from continents where name='Oceania'),'Palau','PW','🇵🇼','active'),
((select id from continents where name='Oceania'),'Papua New Guinea','PG','🇵🇬','active'),
((select id from continents where name='Oceania'),'Samoa','WS','🇼🇸','active'),
((select id from continents where name='Oceania'),'Solomon Islands','SB','🇸🇧','active'),
((select id from continents where name='Oceania'),'Tonga','TO','🇹🇴','active'),
((select id from continents where name='Oceania'),'Tuvalu','TV','🇹🇻','active'),
((select id from continents where name='Oceania'),'Vanuatu','VU','🇻🇺','active'),
-- ---------------- DEFUNCT STATES (40) ----------------
((select id from continents where name='Defunct / Unrecognized'),'USSR',null,'☭','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Yugoslavia',null,'▨','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'East Germany',null,'▤','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Czechoslovakia',null,'▧','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Confederate States',null,'✦','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'West Germany',null,'🦅','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Weimar Republic',null,'🏛','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Russian Empire',null,'👑','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Austria-Hungary',null,'⚜','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Ottoman Empire',null,'☪','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Prussia',null,'✠','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Papal States',null,'🔑','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Free City of Danzig',null,'⚓','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Bohemia and Moravia',null,'🏰','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Serbia and Montenegro',null,'▩','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Rhodesia',null,'🦁','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Zaire',null,'🐆','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Biafra',null,'☀','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Katanga',null,'✚','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Zanzibar',null,'🌶','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Belgian Congo',null,'⭐','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'French West Africa',null,'🌍','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'German East Africa',null,'🏝','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'South Vietnam',null,'☰','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'French Indochina',null,'🐉','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Burma',null,'☸','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Siam',null,'🐘','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Ceylon',null,'🌴','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'British India',null,'♛','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Persia',null,'🦁','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Tibet',null,'🏔','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Manchukuo',null,'🌸','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Sikkim',null,'⛰','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'East Pakistan',null,'🌙','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'South Yemen',null,'★','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'North Yemen',null,'☽','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Straits Settlements',null,'⛵','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Netherlands Antilles',null,'🏖','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Kingdom of Hawaii',null,'🌺','defunct'),
((select id from continents where name='Defunct / Unrecognized'),'Republic of Texas',null,'✰','defunct'),
-- ---------------- UNRECOGNIZED / PARTIALLY RECOGNIZED (6) ----------------
((select id from continents where name='Defunct / Unrecognized'),'Somaliland',null,'🏴','unrecognized'),
((select id from continents where name='Defunct / Unrecognized'),'Transnistria',null,'🏴','unrecognized'),
((select id from continents where name='Defunct / Unrecognized'),'Abkhazia',null,'🏴','unrecognized'),
((select id from continents where name='Defunct / Unrecognized'),'South Ossetia',null,'🏴','unrecognized'),
((select id from continents where name='Defunct / Unrecognized'),'Northern Cyprus',null,'🏴','unrecognized'),
((select id from continents where name='Defunct / Unrecognized'),'Western Sahara','EH','🇪🇭','unrecognized')
on conflict (name) do update
  set continent_id = excluded.continent_id,
      iso_code     = excluded.iso_code,
      flag_emoji   = excluded.flag_emoji,
      status       = excluded.status;

-- sanity check: should return ~243
select count(*) as total_countries from countries;
